-- Pass 3I: the public quote link. public_token is the only key to the
-- customer-facing page: at least 32 random URL-safe bytes, generated by the
-- app when a quote is first marked sent and kept thereafter, so a quote
-- returned to draft and re-sent keeps its link. first_viewed_at records the
-- first public view of a sent quote, set once and never overwritten.
--
-- No RLS change: the public page reads via the service role scoped by
-- token, the same pattern as the webhook design (docs/architecture.md
-- section 8) and the second sanctioned service-role surface after
-- audit-log writes.

alter table public.quotes
  add column public_token text unique;

alter table public.quotes
  add column first_viewed_at timestamptz;
