-- Open the admin write path for a workspace's brand colour (Branding settings,
-- part 1). Until now organisations.brand_color was platform/seed-set only: the
-- migration 0003 column-level update carve-out granted user sessions UPDATE on
-- only (name, custom_field_definitions), so even a client_admin could not change
-- brand_color through their own session.
--
-- This extends that carve-out to include brand_color (and nothing else). The row
-- and role limits are unchanged and already enforced by the existing
-- organisations_update_admin_or_staff policy (migration 0003): the USING/CHECK is
-- is_org_admin(id) or is_platform_staff(), so a non-admin member cannot update,
-- and no one can touch another organisation's row. The column grant is what
-- scopes a user session to specific columns, so adding brand_color here is the
-- whole change: a client_admin may now set brand_color on their own organisation,
-- still cannot set slug/entitlements/etc. (not granted), and still cannot reach
-- another org's row (the policy). This is a user-session, RLS-enforced write, not
-- a new service-role surface. logo_url will be added the same way in the logo pass.
--
-- KEEP IN SYNC WITH scripts/local-reset-grants.sql: that local-reset helper
-- re-applies the organisations column carve-out after its blanket grant, so its
-- grant statement now lists brand_color too. Proven by npm run test:admin-config-rls.

grant update (brand_color) on public.organisations to authenticated;
